---
# tasks file for ansible-elk
- hosts: elk
  remote_user: centos
  become_method : sudo
  become: yes
  gather_facts: yes

  tasks:
    - name: Setting SELinux to permissive
      selinux: policy=targeted state=permissive

#    - name: Install Java 8
#      include_tasks: java.yml

    - name: Install Elasticsearch
      include_tasks: elasticsearch.yml

    - name: Install Kibana
      include_tasks: kibana.yml

    - name: Install Nginx
      include_tasks: nginx.yml

    - name: Install Logstash
      include_tasks: logstash.yml

    - name: Load Kibana dashboards
      include_tasks: dashboard.yml 
